apiVersion: v1
kind: Service
metadata:
  name: cp-slashbot-service
  labels:
    app: cp-slashbot-service
spec:
  ports:
  - port: 4567
    name: http
    targetPort: 4567
  selector:
    app: cp-slashbot
